// 本文件由 docs/contracts/product/product-entry-catalog.v1.json 通过 scripts/release/generate-product-entry-consumers.mjs 生成，禁止手工修改。

export const productEntryCatalogSourceSha256 =
  "178954986bb5d083a87c00bbe7fa515d4f490aaf90f47432d8820412f90991a6" as const;

export const productEntryCatalogContract = {
  schemaVersion: "1.0.0",
  catalogId: "medkernel-product-entry-catalog",
  description:
    "MedKernel 集团医疗智能中枢 35 个客户可见产品入口的唯一合同。职责仅表达固定系统责任，组织与数据范围始终取当前有效分配的交集。",
  initialEvidenceSources: [
    "medkernel-backend/src/main/java/com/medkernel/engine/security/MenuPermissionCatalog.java",
    "frontend/src/shared/config/routes.ts",
    "medkernel-backend/src/main/java/com/medkernel/engine/security/DefaultPermissionPolicy.java",
    "docs/audit/product-function-catalog.md",
    "docs/audit/product-role-journeys.md",
  ],
  responsibilityRoles: ["platform-admin", "engine-operator", "clinical-user", "auditor"],
  sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
  organizationScopeContract: {
    mode: "effective-assignment-intersection",
    tenantBound: true,
    dataPermissionCodes: ["data.department", "data.hospital", "data.group", "data.desensitized"],
    description:
      "按当前服务机构、人员有效任职组织范围与 data.* 数据权限取交集；任何入口及动作都不得扩大该范围。",
  },
  entries: [
    {
      entryCode: "workbench",
      displayName: "工作台",
      sectionCode: "workbench",
      placement: "primary",
      route: "/dashboard",
      responsibilityRoles: ["platform-admin", "engine-operator", "clinical-user", "auditor"],
      requiredPermissions: ["menu.workbench"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "workbench.view",
          label: "查看当前职责风险、待办和高频任务入口",
          requiredPermission: "menu.workbench",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.workbench.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.workbench.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.workbench",
    },
    {
      entryCode: "tenant-onboarding",
      displayName: "服务机构",
      sectionCode: "organization-people",
      placement: "primary",
      route: "/tenant/onboarding",
      responsibilityRoles: ["platform-admin"],
      requiredPermissions: ["menu.tenant-onboarding", "tenant.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "tenant-onboarding.maintain",
          label: "维护服务机构、稳定组织层级和机构类型",
          requiredPermission: "tenant.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.tenant-onboarding.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.tenant-onboarding.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.tenant-onboarding",
    },
    {
      entryCode: "admin-users",
      displayName: "人员与账号",
      sectionCode: "organization-people",
      placement: "primary",
      route: "/admin/users",
      responsibilityRoles: ["platform-admin"],
      requiredPermissions: ["menu.admin-users", "org.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "admin-users.maintain",
          label: "维护自然人、任职、账号、职责和组织范围",
          requiredPermission: "org.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.admin-users.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.admin-users.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.admin-users",
    },
    {
      entryCode: "identity-bindings",
      displayName: "身份来源",
      sectionCode: "organization-people",
      placement: "primary",
      route: "/security/identity-binding",
      responsibilityRoles: ["platform-admin"],
      requiredPermissions: ["menu.identity-bindings", "org.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "identity-bindings.maintain",
          label: "维护统一身份、员工号和证书的单个或批量绑定",
          requiredPermission: "org.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.identity-bindings.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.identity-bindings.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.identity-bindings",
    },
    {
      entryCode: "knowledge-governance",
      displayName: "知识审核发布中心",
      sectionCode: "knowledge-governance",
      placement: "primary",
      route: "/knowledge/governance",
      responsibilityRoles: ["engine-operator"],
      requiredPermissions: ["menu.knowledge-governance", "knowledge.review"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "knowledge-governance.review-publish",
          label: "审核统一候选池中的平台主源或机构派生差异并发布、退修或驳回",
          requiredPermission: "knowledge.review",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.knowledge-governance.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.knowledge-governance.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.knowledge-governance",
    },
    {
      entryCode: "runtime-releases",
      displayName: "机构生效版本",
      sectionCode: "knowledge-governance",
      placement: "primary",
      route: "/config/releases",
      responsibilityRoles: ["engine-operator"],
      requiredPermissions: ["menu.runtime-releases", "asset.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "runtime-releases.publish-tenant-version",
          label: "发布平台标准版本、生成机构生效版本并保留影响和回滚证据",
          requiredPermission: "asset.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.runtime-releases.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.runtime-releases.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.runtime-releases",
    },
    {
      entryCode: "institution-knowledge",
      displayName: "机构知识库",
      sectionCode: "knowledge-governance",
      placement: "primary",
      route: "/knowledge/institution",
      responsibilityRoles: ["engine-operator"],
      requiredPermissions: ["menu.institution-knowledge", "knowledge.write"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "institution-knowledge.derive",
          label: "从平台标准派生机构版本、查看机构覆盖血缘并恢复平台标准",
          requiredPermission: "knowledge.write",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.institution-knowledge.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.institution-knowledge.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.institution-knowledge",
    },
    {
      entryCode: "diagnosis-knowledge",
      displayName: "诊断知识库",
      sectionCode: "knowledge-governance",
      placement: "primary",
      route: "/knowledge/diagnosis",
      responsibilityRoles: ["engine-operator"],
      requiredPermissions: ["menu.diagnosis-knowledge", "knowledge.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "diagnosis-knowledge.maintain",
          label: "管理诊断身份、诊断标准、鉴别诊断、验证病例与来源证据",
          requiredPermission: "knowledge.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.diagnosis-knowledge.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.diagnosis-knowledge.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.diagnosis-knowledge",
    },
    {
      entryCode: "terminology-mapping",
      displayName: "术语字典",
      sectionCode: "knowledge-governance",
      placement: "primary",
      route: "/terminology/mapping",
      responsibilityRoles: ["engine-operator"],
      requiredPermissions: ["menu.terminology-mapping", "term.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "terminology-mapping.reconcile",
          label: "校准院内术语映射、裁定冲突并逐条确认高危近似",
          requiredPermission: "term.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.terminology-mapping.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.terminology-mapping.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.terminology-mapping",
    },
    {
      entryCode: "domain-facade-b0-evidence",
      displayName: "领域门面无模型证据",
      sectionCode: "knowledge-governance",
      placement: "primary",
      route: "/knowledge/domain-facades/b0-evidence",
      responsibilityRoles: ["engine-operator"],
      requiredPermissions: ["menu.domain-facade-b0-evidence", "knowledge.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "domain-facade-b0-evidence.verify",
          label:
            "核查 17 张专业领域门面复用无模型 B0 主链路、缺资产诚实空态和无新增专属业务引擎边界",
          requiredPermission: "knowledge.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.domain-facade-b0-evidence.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.domain-facade-b0-evidence.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.domain-facade-b0-evidence",
    },
    {
      entryCode: "rule-definitions",
      displayName: "临床规则",
      sectionCode: "knowledge-governance",
      placement: "primary",
      route: "/rule/definitions",
      responsibilityRoles: ["engine-operator"],
      requiredPermissions: ["menu.rule-definitions", "rule.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "rule-definitions.manage",
          label: "配置、试运行、审核和发布临床规则",
          requiredPermission: "rule.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.rule-definitions.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.rule-definitions.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.rule-definitions",
    },
    {
      entryCode: "pathway-templates",
      displayName: "临床路径库",
      sectionCode: "knowledge-governance",
      placement: "primary",
      route: "/pathway/templates",
      responsibilityRoles: ["engine-operator"],
      requiredPermissions: ["menu.pathway-templates", "pathway.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "pathway-templates.manage",
          label: "编排、审核、发布和回滚临床路径版本",
          requiredPermission: "pathway.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.pathway-templates.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.pathway-templates.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.pathway-templates",
    },
    {
      entryCode: "provenance",
      displayName: "来源与血缘",
      sectionCode: "knowledge-governance",
      placement: "primary",
      route: "/advanced/provenance",
      responsibilityRoles: ["engine-operator", "auditor"],
      requiredPermissions: ["menu.provenance", "knowledge.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "provenance.trace",
          label: "按来源、版本和引用锚点追溯知识证据",
          requiredPermission: "knowledge.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.provenance.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.provenance.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.provenance",
    },
    {
      entryCode: "graph-explore",
      displayName: "知识关系",
      sectionCode: "knowledge-governance",
      placement: "primary",
      route: "/advanced/graph",
      responsibilityRoles: ["engine-operator"],
      requiredPermissions: ["menu.graph-explore", "projection.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "graph-explore.query",
          label: "查询可重建的知识关系投影",
          requiredPermission: "projection.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.graph-explore.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.graph-explore.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.graph-explore",
    },
    {
      entryCode: "knowledge-production",
      displayName: "知识生产工作台",
      sectionCode: "knowledge-production",
      placement: "primary",
      route: "/knowledge/production",
      responsibilityRoles: ["engine-operator"],
      requiredPermissions: ["menu.knowledge-production", "knowledge.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "knowledge-production.review",
          label:
            "核查知识生产准备、生产任务、候选血缘、安全校验、候选分流、影子证据和高敏患者上下文用途确认重试",
          requiredPermission: "knowledge.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.knowledge-production.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.knowledge-production.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.knowledge-production",
    },
    {
      entryCode: "ai-workflows",
      displayName: "模型能力与安全",
      sectionCode: "knowledge-production",
      placement: "primary",
      route: "/advanced/ai-workflows",
      responsibilityRoles: ["engine-operator"],
      requiredPermissions: ["menu.ai-workflows", "llm.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "ai-workflows.inspect-safety",
          label: "查看模型能力、安全边界和诚实降级状态",
          requiredPermission: "llm.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.ai-workflows.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.ai-workflows.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.ai-workflows",
    },
    {
      entryCode: "mpi",
      displayName: "患者索引",
      sectionCode: "clinical-collaboration",
      placement: "primary",
      route: "/mpi",
      responsibilityRoles: ["clinical-user"],
      requiredPermissions: ["menu.mpi"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "mpi.inspect",
          label: "在授权范围内核查患者主索引和合并拆分问题",
          requiredPermission: "menu.mpi",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.mpi.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.mpi.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.mpi",
    },
    {
      entryCode: "patient-pathways",
      displayName: "患者路径",
      sectionCode: "clinical-collaboration",
      placement: "primary",
      route: "/pathway/patients",
      responsibilityRoles: ["clinical-user"],
      requiredPermissions: ["menu.patient-pathways"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "patient-pathways.handle",
          label: "查看并处理患者路径节点、时钟和变异",
          requiredPermission: "menu.patient-pathways",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.patient-pathways.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.patient-pathways.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.patient-pathways",
    },
    {
      entryCode: "cdss-fatigue",
      displayName: "提醒与推荐",
      sectionCode: "clinical-collaboration",
      placement: "primary",
      route: "/cdss/fatigue",
      responsibilityRoles: ["clinical-user"],
      requiredPermissions: ["menu.cdss-fatigue"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "cdss-fatigue.review",
          label: "查看推荐、来源、处置状态和反馈闭环",
          requiredPermission: "menu.cdss-fatigue",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.cdss-fatigue.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.cdss-fatigue.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.cdss-fatigue",
    },
    {
      entryCode: "workflow-todos",
      displayName: "协同任务",
      sectionCode: "clinical-collaboration",
      placement: "primary",
      route: "/workflow/todos",
      responsibilityRoles: ["clinical-user"],
      requiredPermissions: ["menu.workflow-todos"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "workflow-todos.handle",
          label: "处理、转派、升级和完成职责范围内任务",
          requiredPermission: "menu.workflow-todos",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.workflow-todos.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.workflow-todos.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.workflow-todos",
    },
    {
      entryCode: "clinical-followup",
      displayName: "随访协同",
      sectionCode: "clinical-collaboration",
      placement: "primary",
      route: "/clinical/followup",
      responsibilityRoles: ["engine-operator", "clinical-user"],
      requiredPermissions: ["menu.clinical-followup"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "clinical-followup.coordinate",
          label: "生成随访计划、处理任务和异常回院事件",
          requiredPermission: "menu.clinical-followup",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.clinical-followup.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.clinical-followup.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.clinical-followup",
    },
    {
      entryCode: "sandbox",
      displayName: "全真体验沙盘",
      sectionCode: "clinical-collaboration",
      placement: "primary",
      route: "/sandbox",
      responsibilityRoles: ["engine-operator", "clinical-user"],
      requiredPermissions: ["menu.sandbox", "sandbox.run"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "sandbox.replay",
          label: "以院内业务系统视角复演真实医疗智能链路、嵌入终端与人工反馈闭环",
          requiredPermission: "sandbox.run",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.sandbox.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.sandbox.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.sandbox",
    },
    {
      entryCode: "qc-dashboard",
      displayName: "质量风险概览",
      sectionCode: "quality-management",
      placement: "primary",
      route: "/qc/dashboard",
      responsibilityRoles: ["engine-operator"],
      requiredPermissions: ["menu.qc-dashboard", "evaluation.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "qc-dashboard.inspect",
          label: "查看质量风险、运营趋势并下钻到责任问题",
          requiredPermission: "evaluation.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.qc-dashboard.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.qc-dashboard.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.qc-dashboard",
    },
    {
      entryCode: "qc-alerts",
      displayName: "质量问题与整改",
      sectionCode: "quality-management",
      placement: "primary",
      route: "/qc/alerts",
      responsibilityRoles: ["engine-operator"],
      requiredPermissions: ["menu.qc-alerts", "evaluation.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "qc-alerts.remediate",
          label: "确认问题、派发整改、复核并闭环",
          requiredPermission: "evaluation.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.qc-alerts.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.qc-alerts.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.qc-alerts",
    },
    {
      entryCode: "insurance-audit",
      displayName: "医保审核",
      sectionCode: "quality-management",
      placement: "primary",
      route: "/qc/insurance",
      responsibilityRoles: ["engine-operator"],
      requiredPermissions: ["menu.insurance-audit", "evaluation.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "insurance-audit.review",
          label: "核查医保问题、依据和处置结果",
          requiredPermission: "evaluation.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.insurance-audit.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.insurance-audit.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.insurance-audit",
    },
    {
      entryCode: "qc-eval-sets",
      displayName: "评价指标",
      sectionCode: "quality-management",
      placement: "primary",
      route: "/qc/eval/sets",
      responsibilityRoles: ["engine-operator"],
      requiredPermissions: ["menu.qc-eval-sets", "evaluation.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "qc-eval-sets.manage",
          label: "定义评价指标、试算影响分析并发布生效",
          requiredPermission: "evaluation.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.qc-eval-sets.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.qc-eval-sets.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.qc-eval-sets",
    },
    {
      entryCode: "admin-audit",
      displayName: "审计与证据",
      sectionCode: "compliance-security",
      placement: "primary",
      route: "/admin/audit",
      responsibilityRoles: ["platform-admin", "engine-operator", "auditor"],
      requiredPermissions: ["menu.admin-audit", "audit.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "admin-audit.trace",
          label: "按人员、对象、动作和时间追溯并受控导出证据",
          requiredPermission: "audit.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.admin-audit.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.admin-audit.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.admin-audit",
    },
    {
      entryCode: "security-baseline",
      displayName: "安全与配置",
      sectionCode: "compliance-security",
      placement: "primary",
      route: "/security/baseline",
      responsibilityRoles: ["platform-admin", "auditor"],
      requiredPermissions: ["menu.security-baseline", "system.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "security-baseline.maintain",
          label: "维护安全基线、系统配置、数据权限和脱敏策略",
          requiredPermission: "system.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.security-baseline.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.security-baseline.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.security-baseline",
    },
    {
      entryCode: "implementation-guide",
      displayName: "实施与验收",
      sectionCode: "system-operations",
      placement: "primary",
      route: "/onboarding/guide",
      responsibilityRoles: ["platform-admin"],
      requiredPermissions: ["menu.implementation-guide", "tenant.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "implementation-guide.accept",
          label: "完成机构开通、初始化、联调和交付验收",
          requiredPermission: "tenant.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.implementation-guide.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.implementation-guide.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.implementation-guide",
    },
    {
      entryCode: "adapter-hub",
      displayName: "系统接入",
      sectionCode: "system-operations",
      placement: "primary",
      route: "/adapter/hub",
      responsibilityRoles: ["platform-admin"],
      requiredPermissions: [
        "menu.adapter-hub",
        "integration.read",
        "integration.write",
        "integration.execute",
      ],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "adapter-hub.govern",
          label: "治理外部系统接入、字段映射、健康检查和失败补偿",
          requiredPermission: "integration.execute",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.adapter-hub.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.adapter-hub.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.adapter-hub",
    },
    {
      entryCode: "system-providers",
      displayName: "服务运行保障",
      sectionCode: "system-operations",
      placement: "primary",
      route: "/system/providers",
      responsibilityRoles: ["platform-admin"],
      requiredPermissions: ["menu.system-providers", "system.read"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "system-providers.inspect",
          label: "查看外部依赖、备份恢复、降级和部署健康状态",
          requiredPermission: "system.read",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.system-providers.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.system-providers.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.system-providers",
    },
    {
      entryCode: "runtime-diagnostics",
      displayName: "运行诊断",
      sectionCode: "system-operations",
      placement: "primary",
      route: "/system/runtime-diagnostics",
      responsibilityRoles: ["platform-admin"],
      requiredPermissions: ["menu.runtime-diagnostics"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "runtime-diagnostics.diagnose",
          label: "由信息科和实施角色执行受控诊断",
          requiredPermission: "menu.runtime-diagnostics",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.runtime-diagnostics.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.runtime-diagnostics.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.runtime-diagnostics",
    },
    {
      entryCode: "domestic-check",
      displayName: "国产化适配自检",
      sectionCode: "system-operations",
      placement: "primary",
      route: "/advanced/domestic",
      responsibilityRoles: ["platform-admin"],
      requiredPermissions: ["menu.domestic-check"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "domestic-check.verify",
          label: "核查国产化适配与部署证据",
          requiredPermission: "menu.domestic-check",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.domestic-check.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.domestic-check.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.domestic-check",
    },
    {
      entryCode: "notifications",
      displayName: "消息通知",
      sectionCode: "workbench",
      placement: "header",
      route: "/notifications",
      responsibilityRoles: ["platform-admin", "engine-operator", "clinical-user", "auditor"],
      requiredPermissions: ["menu.notifications"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "notifications.review",
          label: "查看未读消息并跳转到对应业务任务",
          requiredPermission: "menu.notifications",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.notifications.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.notifications.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.notifications",
    },
    {
      entryCode: "notification-settings",
      displayName: "通知偏好",
      sectionCode: "workbench",
      placement: "profile",
      route: "/notifications/settings",
      responsibilityRoles: ["platform-admin", "engine-operator", "clinical-user", "auditor"],
      requiredPermissions: ["menu.notification-settings"],
      organizationScopeMode: "effective-assignment-intersection",
      coreActions: [
        {
          actionCode: "notification-settings.maintain",
          label: "维护个人通知偏好和有权限的机构默认策略",
          requiredPermission: "menu.notification-settings",
        },
      ],
      consumerReadback: {
        required: true,
        strategy: "authoritative-service-state",
        evidenceKey: "catalog.entries.notification-settings.readback",
      },
      auditReadback: {
        required: true,
        strategy: "shared-audit-event",
        eventContract: "shared-audit-event.v1",
        evidenceKey: "catalog.entries.notification-settings.audit",
      },
      sixStates: ["loading", "empty", "ready", "error", "forbidden", "degraded"],
      evidenceKey: "catalog.entries.notification-settings",
    },
  ],
} as const;

export const productEntryCatalog = productEntryCatalogContract.entries;

export type ProductEntry = (typeof productEntryCatalog)[number];
export type ProductEntryCode = ProductEntry["entryCode"];
export type ProductResponsibilityRole =
  (typeof productEntryCatalogContract.responsibilityRoles)[number];
export type ProductSixState = (typeof productEntryCatalogContract.sixStates)[number];
