-- MedKernel 第二阶段 P2-A · LLM-08 模型 provider 真实接入配置（达梦 DM）
-- ROLLBACK：确认无引用后 DROP TABLE mk_llm_provider。credential_ref 仅存密钥引用，绝不落明文。

CREATE TABLE mk_llm_provider (
    id              NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       VARCHAR2(64)  NOT NULL,
    provider_code   VARCHAR2(64)  NOT NULL,
    provider_type   VARCHAR2(32)  NOT NULL,
    endpoint_uri    VARCHAR2(512) NOT NULL,
    credential_ref  VARCHAR2(128) NULL,
    model_version   VARCHAR2(64)  NULL,
    enabled_flag    CHAR(1)       DEFAULT 'Y' NOT NULL,
    status          VARCHAR2(32)  DEFAULT 'NOT_CONNECTED' NOT NULL,
    created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR2(64)  DEFAULT 'system' NOT NULL,
    updated_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by      VARCHAR2(64)  DEFAULT 'system' NOT NULL,
    CONSTRAINT uk_mk_llm_provider_tenant_code UNIQUE (tenant_id, provider_code),
    CONSTRAINT ck_mk_llm_provider_type CHECK (provider_type IN ('OLLAMA', 'OPENAI_COMPATIBLE', 'CLAUDE', 'DIFY')),
    CONSTRAINT ck_mk_llm_provider_enabled CHECK (enabled_flag IN ('Y', 'N'))
);

CREATE INDEX idx_mk_llm_provider_tenant ON mk_llm_provider (tenant_id, provider_type);
