-- MedKernel 第二阶段 P2-B · LLM-05 全业务模型增强接入矩阵（达梦 DM）
-- 平台全局「模型网关全局目录」增强接入图谱：业务点 ↔ 能力码 ↔ B0 路径 ↔ 接入状态。
-- ROLLBACK：确认无引用后 DROP TABLE mk_llm_enhancement_matrix。

CREATE TABLE mk_llm_enhancement_matrix (
    id              NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_point  VARCHAR2(64)  NOT NULL,
    business_name   VARCHAR2(128) NOT NULL,
    capability_code VARCHAR2(64)  NULL,
    b0_path         VARCHAR2(512) NULL,
    access_status   VARCHAR2(24)  DEFAULT 'PENDING' NOT NULL,
    enabled_flag    CHAR(1)       DEFAULT 'Y' NOT NULL,
    sort_order      NUMBER(10)    DEFAULT 100 NOT NULL,
    created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR2(64)  DEFAULT 'system' NOT NULL,
    updated_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by      VARCHAR2(64)  DEFAULT 'system' NOT NULL,
    CONSTRAINT uk_mk_llm_enhancement_matrix_point UNIQUE (business_point),
    CONSTRAINT ck_mk_llm_enhancement_matrix_status CHECK (access_status IN ('PENDING', 'ACTIVE', 'DISABLED')),
    CONSTRAINT ck_mk_llm_enhancement_matrix_enabled CHECK (enabled_flag IN ('Y', 'N'))
);

CREATE INDEX idx_mk_llm_enhancement_matrix_status ON mk_llm_enhancement_matrix (access_status, sort_order);

INSERT INTO mk_llm_enhancement_matrix (business_point, business_name, capability_code, b0_path, access_status, sort_order) VALUES ('knowledge-discovery', '临床知识关联发现', 'knowledge.discovery', '确定性知识检索与关联基线', 'ACTIVE', 10);
INSERT INTO mk_llm_enhancement_matrix (business_point, business_name, capability_code, b0_path, access_status, sort_order) VALUES ('knowledge-extract', '电子病历语义实体提取', 'knowledge.extract', '规则化结构实体抽取基线', 'ACTIVE', 20);
INSERT INTO mk_llm_enhancement_matrix (business_point, business_name, capability_code, b0_path, access_status, sort_order) VALUES ('terminology', '标准术语字典匹配映射', 'terminology.map', '确定性术语映射基线', 'ACTIVE', 30);
INSERT INTO mk_llm_enhancement_matrix (business_point, business_name, capability_code, b0_path, access_status, sort_order) VALUES ('rule', '临床规则草案拟定', 'rule.draft', '确定性规则模板基线', 'ACTIVE', 40);
INSERT INTO mk_llm_enhancement_matrix (business_point, business_name, capability_code, b0_path, access_status, sort_order) VALUES ('pathway', '临床路径草案拟定', 'pathway.draft', '确定性路径模板基线', 'ACTIVE', 50);
INSERT INTO mk_llm_enhancement_matrix (business_point, business_name, capability_code, b0_path, access_status, sort_order) VALUES ('cdss', '临床决策解释', 'cdss.explain', '确定性决策依据解释基线', 'ACTIVE', 60);
INSERT INTO mk_llm_enhancement_matrix (business_point, business_name, capability_code, b0_path, access_status, sort_order) VALUES ('quality', '病历内涵质控', 'quality.semantic-check', '确定性质控规则基线', 'ACTIVE', 70);
INSERT INTO mk_llm_enhancement_matrix (business_point, business_name, capability_code, b0_path, access_status, sort_order) VALUES ('followup', '随访草案拟定', 'followup.draft', '确定性随访模板基线', 'ACTIVE', 80);
INSERT INTO mk_llm_enhancement_matrix (business_point, business_name, capability_code, b0_path, access_status, sort_order) VALUES ('nursing', '护理知识增强', NULL, NULL, 'PENDING', 90);
INSERT INTO mk_llm_enhancement_matrix (business_point, business_name, capability_code, b0_path, access_status, sort_order) VALUES ('report', '报告解读增强', NULL, NULL, 'PENDING', 100);
