-- MedKernel 第二阶段 P2-B · DATASVC-01 引擎数据服务层异步导出作业（达梦 DM）
-- 三组 D2 去标识聚合读模型经 SYS-06 导出审批闸控制后异步 CSV 导出；审批锚点 approval_id/idempotency_key/request_snapshot。
-- ROLLBACK：确认无引用后 DROP TABLE mk_engine_data_export_job。

CREATE TABLE mk_engine_data_export_job (
    id               NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        VARCHAR2(64)   NOT NULL,
    job_code         VARCHAR2(64)   NOT NULL,
    requested_by     VARCHAR2(64)   NOT NULL,
    export_type      VARCHAR2(32)   NOT NULL,
    status           VARCHAR2(16)   DEFAULT 'PENDING' NOT NULL,
    progress         NUMBER(10)     DEFAULT 0 NOT NULL,
    result_uri       VARCHAR2(512)  NULL,
    item_count       NUMBER(19)     NULL,
    error_message    VARCHAR2(1024) NULL,
    approval_id      VARCHAR2(128)  NOT NULL,
    idempotency_key  VARCHAR2(128)  NOT NULL,
    request_snapshot VARCHAR2(2000) NOT NULL,
    created_at       TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    started_at       TIMESTAMP      NULL,
    completed_at     TIMESTAMP      NULL,
    expires_at       TIMESTAMP      NULL,
    CONSTRAINT uk_mk_engine_data_export_job_code UNIQUE (job_code),
    CONSTRAINT uk_mk_engine_data_export_job_idem UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT ck_mk_engine_data_export_job_type CHECK (export_type IN ('RULE_USAGE', 'KNOWLEDGE_USAGE', 'CLINICAL_SIGNALS')),
    CONSTRAINT ck_mk_engine_data_export_job_status CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'EXPIRED'))
);

CREATE INDEX idx_mk_engine_data_export_job_tenant ON mk_engine_data_export_job (tenant_id, created_at);
