-- MedKernel 第二阶段 P2-B · LLM-06 可信来源探索运行存证（达梦 DM）
-- 受控来源确定性探索（B0）的检索时点存证：记录检索时点 + 当时源版本快照 + 结果集真实指纹，复查「当时看到什么」。
-- ROLLBACK：确认无引用后 DROP TABLE mk_knowledge_discovery_run。

CREATE TABLE mk_knowledge_discovery_run (
    id               NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        VARCHAR2(64)   NOT NULL,
    run_code         VARCHAR2(64)   NOT NULL,
    query_text       VARCHAR2(512)  NOT NULL,
    capability_code  VARCHAR2(64)   NOT NULL,
    executed_at      TIMESTAMP      NOT NULL,
    source_snapshot  VARCHAR2(4000) NOT NULL,
    hit_count        NUMBER(10)     DEFAULT 0 NOT NULL,
    candidate_count  NUMBER(10)     DEFAULT 0 NOT NULL,
    result_hash      VARCHAR2(64)   NOT NULL,
    status           VARCHAR2(16)   NOT NULL,
    degraded         NUMBER(1)      DEFAULT 0 NOT NULL,
    created_by       VARCHAR2(64)   NULL,
    created_at       TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_mk_knowledge_discovery_run_code UNIQUE (run_code),
    CONSTRAINT ck_mk_knowledge_discovery_run_status CHECK (status IN ('SUCCEEDED', 'EMPTY', 'DEGRADED'))
);

CREATE INDEX idx_mk_knowledge_discovery_run_tenant ON mk_knowledge_discovery_run (tenant_id, executed_at);

COMMENT ON TABLE mk_knowledge_discovery_run IS '可信来源探索运行存证：受控来源确定性探索的检索时点存证，记录检索时点与当时源版本快照及结果集真实指纹，供复查当时看到什么';
