-- MedKernel 第二阶段 P2-C · AIK-STD-10 生成期知识候选 8 态分流（达梦 DM）
-- 生成期记录候选身份识别、去重、8 态分流与处理去向；append-only 审计轨迹。
-- ROLLBACK：确认无引用后 DROP TABLE mk_knowledge_generation_triage。

CREATE TABLE mk_knowledge_generation_triage (
    id                 NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          VARCHAR2(64)  NOT NULL,
    job_code           VARCHAR2(64)  NOT NULL,
    content_hash       VARCHAR2(64)  NOT NULL,
    asset_type         VARCHAR2(32)  NOT NULL,
    target_identity_id NUMBER(19)    NULL,
    active_version_id  NUMBER(19)    NULL,
    matched_version_id NUMBER(19)    NULL,
    triage_state       VARCHAR2(32)  NOT NULL,
    action             VARCHAR2(32)  NOT NULL,
    basis              VARCHAR2(512) NOT NULL,
    created_at         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by         VARCHAR2(64)  NULL,
    CONSTRAINT ck_mk_knowledge_generation_triage_state CHECK (triage_state IN
        ('NEW_ASSET','DUPLICATE','MINOR_REVISION','MAJOR_UPGRADE','CONFLICT','DOWNGRADE','DEPRECATION','UNCERTAIN')),
    CONSTRAINT ck_mk_knowledge_generation_triage_action CHECK (action IN
        ('SUBMIT_REVIEW','SKIP_DUPLICATE','MERGE_REVIEW','UPGRADE_REVIEW','CONFLICT_REVIEW','DOWNGRADE_REVIEW','RETIREMENT_REVIEW','MANUAL_REVIEW'))
);

CREATE INDEX idx_mk_knowledge_generation_triage_job ON mk_knowledge_generation_triage (tenant_id, job_code);
CREATE INDEX idx_mk_knowledge_generation_triage_identity ON mk_knowledge_generation_triage (tenant_id, target_identity_id, created_at);

COMMENT ON TABLE mk_knowledge_generation_triage IS '知识候选生成期分流：记录候选身份识别、去重、8态分流与处理去向，append-only 审计轨迹';
