-- MedKernel 第二阶段 P2-C · AIK-STD-06 生成期影子评测运行记录（达梦 DM）
-- 候选进入人工审核前记录影子评测指标、退化和达标裁决；无基准集不得自动认证。
-- ROLLBACK：确认无引用后 DROP TABLE mk_knowledge_shadow_run。

CREATE TABLE mk_knowledge_shadow_run (
    id                   NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            VARCHAR2(64)  NOT NULL,
    job_code             VARCHAR2(64)  NOT NULL,
    asset_type           VARCHAR2(32)  NOT NULL,
    target_identity_id   NUMBER(19)    NULL,
    content_hash         VARCHAR2(64)  NOT NULL,
    capability_code      VARCHAR2(96)  NOT NULL,
    status               VARCHAR2(24)  NOT NULL,
    total_cases          NUMBER(10)    DEFAULT 0 NOT NULL,
    hit_count            NUMBER(10)    DEFAULT 0 NOT NULL,
    false_positive_count NUMBER(10)    DEFAULT 0 NOT NULL,
    miss_count           NUMBER(10)    DEFAULT 0 NOT NULL,
    degradation_detected NUMBER(1)     DEFAULT 0 NOT NULL,
    ready_for_review     NUMBER(1)     DEFAULT 0 NOT NULL,
    basis                VARCHAR2(512) NOT NULL,
    created_at           TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by           VARCHAR2(64)  NULL,
    CONSTRAINT ck_mk_knowledge_shadow_run_status CHECK (status IN ('NOT_READY','FAILED','PASSED','PENDING_REVIEW')),
    CONSTRAINT ck_mk_knowledge_shadow_run_counts CHECK (
        total_cases >= 0 AND hit_count >= 0 AND false_positive_count >= 0 AND miss_count >= 0
    )
);

CREATE INDEX idx_mk_knowledge_shadow_run_job ON mk_knowledge_shadow_run (tenant_id, job_code);
CREATE INDEX idx_mk_knowledge_shadow_run_status ON mk_knowledge_shadow_run (tenant_id, status, created_at);

COMMENT ON TABLE mk_knowledge_shadow_run IS '知识候选生成期影子评测运行记录：记录回归用例指标、质量退化和是否允许进入人工审核';
