-- MedKernel 第二阶段 P2-C · AIK-STD-07 知识包装配作业（达梦 DM）
-- 新项目基线：只记录当前 AIK 装配清单与包引用，不做旧包兼容回填。

CREATE TABLE aik_pack_job (
    id               NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id           VARCHAR2(64)  NOT NULL,
    tenant_id        VARCHAR2(64)  NOT NULL,
    package_id       VARCHAR2(64)  NOT NULL,
    package_code     VARCHAR2(128) NOT NULL,
    package_version  VARCHAR2(64)  NOT NULL,
    item_count       NUMBER(10)    NOT NULL,
    asset_manifest   CLOB          NOT NULL,
    manifest_sha256  VARCHAR2(64)  NOT NULL,
    status           VARCHAR2(24)  NOT NULL,
    created_at       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by       VARCHAR2(64)  NULL,
    updated_at       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by       VARCHAR2(64)  NULL,
    trace_id         VARCHAR2(128) NULL,
    CONSTRAINT uk_aik_pack_job_id UNIQUE (tenant_id, job_id),
    CONSTRAINT uk_aik_pack_job_package UNIQUE (tenant_id, package_id),
    CONSTRAINT fk_aik_pack_job_package
        FOREIGN KEY (tenant_id, package_id) REFERENCES knowledge_package (tenant_id, package_id),
    CONSTRAINT ck_aik_pack_job_status CHECK (status IN ('PACKAGED','FAILED')),
    CONSTRAINT ck_aik_pack_job_count CHECK (item_count > 0)
);

CREATE INDEX idx_aik_pack_job_package
    ON aik_pack_job (tenant_id, package_code, package_version);
CREATE INDEX idx_aik_pack_job_status
    ON aik_pack_job (tenant_id, status, updated_at);

COMMENT ON TABLE aik_pack_job IS 'AIK-STD-07 知识包装配作业：记录已审知识资产清单、PKG-01 包引用和清单摘要';
COMMENT ON COLUMN aik_pack_job.job_id IS 'AIK 装配作业唯一编码';
COMMENT ON COLUMN aik_pack_job.package_id IS '装配形成的 PKG-01 知识包 ID';
COMMENT ON COLUMN aik_pack_job.asset_manifest IS '入包知识资产清单 JSON，包含身份、版本和内容指纹';
COMMENT ON COLUMN aik_pack_job.manifest_sha256 IS '资产清单 SHA-256 摘要';
COMMENT ON COLUMN aik_pack_job.status IS '装配作业状态：已打包或失败';
