-- MedKernel v1.0 GA · 应急权限授予表（达梦 DM8）
CREATE TABLE emergency_permission_grant (
    id              NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       VARCHAR2(64)  NOT NULL,
    user_id         VARCHAR2(128) NOT NULL,
    permission_code VARCHAR2(128) DEFAULT 'env.emergency' NOT NULL,
    reason          VARCHAR2(512) NOT NULL,
    granted_by      VARCHAR2(128) NOT NULL,
    granted_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at      TIMESTAMP     NOT NULL,
    revoked_at      TIMESTAMP,
    revoked_by      VARCHAR2(128),
    active_flag     CHAR(1)       DEFAULT 'Y' NOT NULL,
    created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR2(64)  DEFAULT 'system' NOT NULL,
    updated_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by      VARCHAR2(64)  DEFAULT 'system' NOT NULL,
    CONSTRAINT ck_emergency_permission_code CHECK (permission_code = 'env.emergency'),
    CONSTRAINT ck_emergency_permission_active CHECK (active_flag IN ('Y','N'))
);

CREATE INDEX idx_emergency_permission_active
    ON emergency_permission_grant (tenant_id, user_id, permission_code, active_flag, expires_at);

CREATE INDEX idx_emergency_permission_expiry
    ON emergency_permission_grant (active_flag, expires_at);

COMMENT ON TABLE emergency_permission_grant IS '应急权限授予记录表，break-glass 权限必须审计且到期自动失效';
