-- B0 第一阶段完美化 · 术语候选生成异步任务（Oracle）
-- 10 万级院内字典候选生成只返回任务与分页入口，不同步返回候选明细。
-- ROLLBACK：确认无引用后 DROP TABLE mk_term_candidate_generation_job，并删除 mapping_candidate.generation_job_code。

CREATE TABLE mk_term_candidate_generation_job (
    id                       NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                VARCHAR2(64)   NOT NULL,
    job_code                 VARCHAR2(64)   NOT NULL,
    source_system            VARCHAR2(64)   NOT NULL,
    minimum_score            NUMBER(8,4)    NULL,
    semantic_assist_enabled  NUMBER(1)      DEFAULT 1 NOT NULL,
    package_version          VARCHAR2(64)   NOT NULL,
    requested_by             VARCHAR2(64)   NOT NULL,
    status                   VARCHAR2(16)   DEFAULT 'PENDING' NOT NULL,
    progress                 NUMBER(10)     DEFAULT 0 NOT NULL,
    generated_count          NUMBER(10)     DEFAULT 0 NOT NULL,
    candidate_page_uri       VARCHAR2(512)  NULL,
    error_message            VARCHAR2(1024) NULL,
    created_at               TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    started_at               TIMESTAMP      NULL,
    completed_at             TIMESTAMP      NULL,
    CONSTRAINT uk_mk_term_candidate_generation_job_code UNIQUE (job_code),
    CONSTRAINT ck_mk_term_candidate_generation_job_status CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED'))
);

ALTER TABLE mapping_candidate ADD (generation_job_code VARCHAR2(64) NULL);

CREATE INDEX idx_mk_term_candidate_generation_job_tenant
    ON mk_term_candidate_generation_job (tenant_id, created_at);
CREATE INDEX idx_mapping_candidate_generation_job
    ON mapping_candidate (tenant_id, generation_job_code, status);

COMMENT ON TABLE mk_term_candidate_generation_job IS '术语候选生成异步任务：保存来源系统、阈值、生成状态、候选数量和分页入口，避免同步返回大批量候选明细';
COMMENT ON COLUMN mapping_candidate.generation_job_code IS '产生该候选的术语候选生成任务编码，用于按任务分页追溯';
