-- MedKernel 全真沙盘 · CURRENT 运行绑定与不可变基线（Oracle）
-- 场景模板不保存固定包版本；每次运行只能从演练机构唯一 ACTIVE 绑定解析并冻结。

CREATE TABLE mk_sandbox_runtime_binding (
    id                       NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    binding_id               VARCHAR2(64)  NOT NULL,
    tenant_id                VARCHAR2(64)  NOT NULL,
    target_org_unit_id       VARCHAR2(64)  NOT NULL,
    package_owner_tenant_id  VARCHAR2(64)  NOT NULL,
    package_id               VARCHAR2(64)  NOT NULL,
    package_code             VARCHAR2(128) NOT NULL,
    package_version          VARCHAR2(64)  NOT NULL,
    status                   VARCHAR2(16)  NOT NULL,
    active_scope_key         VARCHAR2(96)  NULL,
    activated_at             TIMESTAMP    NOT NULL,
    activated_by             VARCHAR2(64)  NOT NULL,
    created_at               TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by               VARCHAR2(64)  NOT NULL,
    updated_at               TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by               VARCHAR2(64)  NOT NULL,
    trace_id                 VARCHAR2(128) NOT NULL,
    CONSTRAINT uk_mk_sandbox_runtime_binding_id UNIQUE (tenant_id, binding_id),
    CONSTRAINT uk_mk_sandbox_runtime_binding_active UNIQUE (active_scope_key),
    CONSTRAINT fk_mk_sandbox_runtime_binding_package
        FOREIGN KEY (package_owner_tenant_id, package_id)
        REFERENCES knowledge_package (tenant_id, package_id),
    CONSTRAINT ck_mk_sandbox_runtime_binding_status CHECK (status IN ('ACTIVE','INACTIVE')),
    CONSTRAINT ck_mk_sandbox_runtime_binding_active CHECK (
        (status = 'ACTIVE' AND active_scope_key = tenant_id || '|ACTIVE')
        OR (status = 'INACTIVE' AND active_scope_key IS NULL)
    )
);

CREATE TABLE mk_sandbox_run (
    id                           NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                       VARCHAR2(64)   NOT NULL,
    tenant_id                    VARCHAR2(64)   NOT NULL,
    scenario_id                  VARCHAR2(128)  NOT NULL,
    mode                         VARCHAR2(32)   NOT NULL,
    binding_id                   VARCHAR2(64)   NULL,
    baseline_id                  VARCHAR2(64)   NOT NULL,
    package_owner_tenant_id      VARCHAR2(64)   NOT NULL,
    package_id                   VARCHAR2(64)   NOT NULL,
    package_code                 VARCHAR2(128)  NOT NULL,
    package_version              VARCHAR2(64)   NOT NULL,
    resolution_source            VARCHAR2(32)   NOT NULL,
    asset_bindings_json          CLOB          NOT NULL,
    baseline_hash                VARCHAR2(64)   NOT NULL,
    external_side_effect_status  VARCHAR2(24)   NOT NULL,
    status                       VARCHAR2(24)   NOT NULL,
    failure_code                 VARCHAR2(64)   NULL,
    failure_message              VARCHAR2(1024) NULL,
    started_at                   TIMESTAMP     NOT NULL,
    completed_at                 TIMESTAMP     NULL,
    trace_id                     VARCHAR2(128)  NOT NULL,
    created_at                   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by                   VARCHAR2(64)   NOT NULL,
    updated_at                   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by                   VARCHAR2(64)   NOT NULL,
    CONSTRAINT uk_mk_sandbox_run_id UNIQUE (tenant_id, run_id),
    CONSTRAINT uk_mk_sandbox_run_baseline UNIQUE (tenant_id, baseline_id),
    CONSTRAINT fk_mk_sandbox_run_binding
        FOREIGN KEY (tenant_id, binding_id)
        REFERENCES mk_sandbox_runtime_binding (tenant_id, binding_id),
    CONSTRAINT fk_mk_sandbox_run_package
        FOREIGN KEY (package_owner_tenant_id, package_id)
        REFERENCES knowledge_package (tenant_id, package_id),
    CONSTRAINT ck_mk_sandbox_run_mode CHECK (mode IN ('CURRENT','HISTORICAL_EXACT','COMPARE')),
    CONSTRAINT ck_mk_sandbox_run_current_binding CHECK (mode <> 'CURRENT' OR binding_id IS NOT NULL),
    CONSTRAINT ck_mk_sandbox_run_resolution CHECK (
        resolution_source IN ('TENANT_PACKAGE','PLATFORM_PACKAGE','REPLAY_MANIFEST')
    ),
    CONSTRAINT ck_mk_sandbox_run_side_effect CHECK (external_side_effect_status = 'SUPPRESSED'),
    CONSTRAINT ck_mk_sandbox_run_status CHECK (status IN ('PREPARING','RUNNING','PASSED','FAILED'))
);

CREATE INDEX idx_mk_sandbox_runtime_binding_tenant
    ON mk_sandbox_runtime_binding (tenant_id, status, activated_at);
CREATE INDEX idx_mk_sandbox_run_tenant_status
    ON mk_sandbox_run (tenant_id, status, started_at);
CREATE INDEX idx_mk_sandbox_run_scenario
    ON mk_sandbox_run (tenant_id, scenario_id, started_at);

COMMENT ON TABLE mk_sandbox_runtime_binding IS '演练机构沙盘运行绑定：唯一 ACTIVE 记录明确指向可运行配置包';
COMMENT ON COLUMN mk_sandbox_runtime_binding.active_scope_key IS 'ACTIVE 绑定的租户唯一键；历史 INACTIVE 绑定必须为空';
COMMENT ON TABLE mk_sandbox_run IS '沙盘运行账本：保存不可变运行基线、解析来源、资产快照和执行状态';
COMMENT ON COLUMN mk_sandbox_run.asset_bindings_json IS '本次解析出的资产版本快照，不得在执行中重新解析';
COMMENT ON COLUMN mk_sandbox_run.baseline_hash IS '不可变运行基线 SHA-256';
COMMENT ON COLUMN mk_sandbox_run.external_side_effect_status IS '外部副作用必须为 SUPPRESSED，禁止现场写回';
