-- MedKernel SYS-05 · 离线、重试与任务死信（Oracle 19c+）
-- ROLLBACK: 如需回滚，先导出 sys_task_dead_letter 死信证据，再删除 V42 新增索引/表/列并恢复 V41 的模式与状态约束。

ALTER TABLE sys_task DROP CONSTRAINT ck_sys_task_mode;
ALTER TABLE sys_task DROP CONSTRAINT ck_sys_task_status;

ALTER TABLE sys_task ADD (
    retry_count           NUMBER(10) DEFAULT 0 NOT NULL,
    max_retries           NUMBER(10) DEFAULT 2 NOT NULL,
    next_attempt_at       TIMESTAMP WITH TIME ZONE,
    last_error_code       VARCHAR2(64),
    dead_letter_id        VARCHAR2(64),
    replayed_from_task_id VARCHAR2(64)
);

ALTER TABLE sys_task ADD CONSTRAINT ck_sys_task_mode
    CHECK (task_mode IN ('ONLINE','ASYNC','BATCH','OFFLINE'));

ALTER TABLE sys_task ADD CONSTRAINT ck_sys_task_status
    CHECK (status IN ('UNREAD','PROCESSING','COMPLETED','PARTIAL_SUCCESS','FAILED','ESCALATED','NOT_CONNECTED','DEAD_LETTER'));

CREATE TABLE sys_task_dead_letter (
    id                   NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dead_letter_id       VARCHAR2(64)  NOT NULL,
    tenant_id            VARCHAR2(64)  NOT NULL,
    org_path             VARCHAR2(512),
    task_id              VARCHAR2(64)  NOT NULL,
    task_mode            VARCHAR2(16)  NOT NULL,
    task_type            VARCHAR2(64)  NOT NULL,
    payload_storage_type VARCHAR2(16),
    payload_uri          VARCHAR2(512),
    payload_digest       VARCHAR2(128),
    payload_size_bytes   NUMBER(19),
    total_count          NUMBER(10)    DEFAULT 0 NOT NULL,
    retry_count          NUMBER(10)    DEFAULT 0 NOT NULL,
    failure_details_json CLOB,
    error_code           VARCHAR2(64),
    message              CLOB,
    trace_id             VARCHAR2(128),
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by           VARCHAR2(64)  NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by           VARCHAR2(64)  NOT NULL,
    replayed_at          TIMESTAMP WITH TIME ZONE,
    replayed_by          VARCHAR2(64),
    replay_task_id       VARCHAR2(64),
    CONSTRAINT uk_sys_task_dead_letter UNIQUE (tenant_id, dead_letter_id),
    CONSTRAINT uk_sys_task_dead_task UNIQUE (tenant_id, task_id),
    CONSTRAINT ck_sys_task_dead_mode CHECK (task_mode IN ('ONLINE','ASYNC','BATCH','OFFLINE'))
);

CREATE INDEX idx_sys_task_retry_ts
    ON sys_task (tenant_id, status, next_attempt_at);

CREATE INDEX idx_sys_task_dead_letter
    ON sys_task (tenant_id, dead_letter_id);

CREATE INDEX idx_sys_task_dead_tenant_ts
    ON sys_task_dead_letter (tenant_id, created_at);

CREATE INDEX idx_sys_task_dead_task
    ON sys_task_dead_letter (task_id, tenant_id);

COMMENT ON COLUMN sys_task.retry_count IS '任务已执行的人工重试次数';
COMMENT ON COLUMN sys_task.max_retries IS '任务允许的最大人工重试次数';
COMMENT ON COLUMN sys_task.next_attempt_at IS '建议的下一次重试时间';
COMMENT ON COLUMN sys_task.dead_letter_id IS '任务进入死信后的死信 ID';
COMMENT ON COLUMN sys_task.replayed_from_task_id IS '死信回放来源任务 ID';
COMMENT ON TABLE sys_task_dead_letter IS 'SYS-05 任务死信表，保存重试耗尽任务的失败证据和人工回放结果';
COMMENT ON COLUMN sys_task_dead_letter.dead_letter_id IS '死信业务 ID，用于人工回放和审计追踪';
COMMENT ON COLUMN sys_task_dead_letter.task_id IS '进入死信的原始任务 ID';
COMMENT ON COLUMN sys_task_dead_letter.replay_task_id IS '人工回放后创建的新任务 ID';
