package com.medkernel.shared.api;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.medkernel.shared.context.OrgScope;
import com.medkernel.shared.context.RequestContext;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * ApiResult 成功响应序列化契约测试 — 锁定对外 JSON 形态。
 * 任何字段重命名、删除都会让本测试失败，迫使做出兼容性决策。
 *
 * <p>失败响应由 {@code ProblemDetail} 承载，不再使用 ApiResult 失败包络。
 */
class ApiResultTest {

    private final ObjectMapper mapper = new ObjectMapper().registerModule(new JavaTimeModule());

    @AfterEach
    void clear() {
        RequestContext.clear();
    }

    @Test
    void okEnvelopeContainsRequiredFields() throws Exception {
        RequestContext.restore(new RequestContext.Snapshot("trace-abc", OrgScope.tenant("t-1"), "u-1"));

        ApiResult<String> result = ApiResult.ok("hello");
        JsonNode node = mapper.valueToTree(result);

        assertThat(node.get("success").asBoolean()).isTrue();
        assertThat(node.get("code").asText()).isEqualTo("OK");
        assertThat(node.get("message").asText()).isEqualTo("操作成功");
        assertThat(node.get("data").asText()).isEqualTo("hello");
        assertThat(node.get("traceId").asText()).isEqualTo("trace-abc");
        assertThat(node.get("timestamp").asText()).isNotBlank();
        assertThat(node.has("errors")).isFalse();
    }

    @Test
    void traceIdAutoGeneratedWhenContextEmpty() {
        RequestContext.clear();
        ApiResult<String> result = ApiResult.ok("x");
        assertThat(result.traceId()).isNull();
    }
}
