package com.medkernel.engine.knowledge.production.initialization;

/** 基础发行版必须完整覆盖的稳定维度。 */
public enum FoundationCoverageDimension {
    SOURCE_LICENSE_MANIFEST,
    DATA_ELEMENT_CATALOG,
    TERMINOLOGY_CODE_SYSTEM,
    VALUE_SET_SYSTEM_ACTION_DICTIONARY,
    UNIT_DIMENSION_ALIAS_CONVERSION,
    MASTER_DATA,
    INTEROPERABILITY_MAPPING_PROFILE,
    SEMANTIC_RELATION_DEPRECATION_REDIRECT,
    EVIDENCE_GRADE_AUTHORITY,
    DEPENDENCY_COMPATIBILITY_IMPACT,
    AUTHORITATIVE_SOURCE_SCOPE,
    GOLDEN_REGRESSION_BOM_COVERAGE
}
